// This code was autogenerated from riskengine/riskengine.proto, do not edit.
package riskengine

import (
	"context"
	"log"
	"time"

	"google.golang.org/protobuf/proto"
	"github.com/nats-io/nats.go"
	github_com_golang_protobuf_ptypes_empty "github.com/golang/protobuf/ptypes/empty"
	"github.com/nats-rpc/nrpc"
)

// RiskEngineServer is the interface that providers of the service
// RiskEngine should implement.
type RiskEngineServer interface {
	RpcAlive(ctx context.Context, req *github_com_golang_protobuf_ptypes_empty.Empty) (*github_com_golang_protobuf_ptypes_empty.Empty, error)
	RpcRiskTxs(ctx context.Context, req *TxRiskReq) (*TxRiskRes, error)
	RpcRiskTfa(ctx context.Context, req *TfaRiskReq) (*TfaRiskRes, error)
}

// RiskEngineHandler provides a NATS subscription handler that can serve a
// subscription using a given RiskEngineServer implementation.
type RiskEngineHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  RiskEngineServer

	encodings []string
}

func NewRiskEngineHandler(ctx context.Context, nc nrpc.NatsConn, s RiskEngineServer) *RiskEngineHandler {
	return &RiskEngineHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,

		encodings: []string{"protobuf"},
	}
}

func NewRiskEngineConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s RiskEngineServer) *RiskEngineHandler {
	return &RiskEngineHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

// SetEncodings sets the output encodings when using a '*Publish' function
func (h *RiskEngineHandler) SetEncodings(encodings []string) {
	h.encodings = encodings
}

func (h *RiskEngineHandler) Subject() string {
	return "RiskEngine.>"
}

func (h *RiskEngineHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, _, name, tail, err := nrpc.ParseSubject(
		"", 0, "RiskEngine", 0, msg.Subject)
	if err != nil {
		log.Printf("RiskEngineHanlder: RiskEngine subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "RpcAlive":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("RpcAliveHanlder: RpcAlive subject parsing failed: %v", err)
			break
		}
		var req github_com_golang_protobuf_ptypes_empty.Empty
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("RpcAliveHandler: RpcAlive request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.RpcAlive(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	case "RpcRiskTxs":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("RpcRiskTxsHanlder: RpcRiskTxs subject parsing failed: %v", err)
			break
		}
		var req TxRiskReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("RpcRiskTxsHandler: RpcRiskTxs request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.RpcRiskTxs(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	case "RpcRiskTfa":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("RpcRiskTfaHanlder: RpcRiskTfa subject parsing failed: %v", err)
			break
		}
		var req TfaRiskReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("RpcRiskTfaHandler: RpcRiskTfa request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.RpcRiskTfa(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	default:
		log.Printf("RiskEngineHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("RiskEngineHandler: RiskEngine handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type RiskEngineClient struct {
	nc      nrpc.NatsConn
	Subject string
	Encoding string
	Timeout time.Duration
}

func NewRiskEngineClient(nc nrpc.NatsConn) *RiskEngineClient {
	return &RiskEngineClient{
		nc:      nc,
		Subject: "RiskEngine",
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *RiskEngineClient) RpcAlive(req *github_com_golang_protobuf_ptypes_empty.Empty) (*github_com_golang_protobuf_ptypes_empty.Empty, error) {

	subject := c.Subject + "." + "RpcAlive"

	// call
	var resp = github_com_golang_protobuf_ptypes_empty.Empty{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *RiskEngineClient) RpcRiskTxs(req *TxRiskReq) (*TxRiskRes, error) {

	subject := c.Subject + "." + "RpcRiskTxs"

	// call
	var resp = TxRiskRes{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *RiskEngineClient) RpcRiskTfa(req *TfaRiskReq) (*TfaRiskRes, error) {

	subject := c.Subject + "." + "RpcRiskTfa"

	// call
	var resp = TfaRiskRes{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

type Client struct {
	nc      nrpc.NatsConn
	defaultEncoding string
	defaultTimeout time.Duration
	RiskEngine *RiskEngineClient
}

func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc: nc,
		defaultEncoding: "protobuf",
		defaultTimeout: 5*time.Second,
	}
	c.RiskEngine = NewRiskEngineClient(nc)
	return &c
}

func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
	if c.RiskEngine != nil {
		c.RiskEngine.Encoding = encoding
	}
}

func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
	if c.RiskEngine != nil {
		c.RiskEngine.Timeout = t
	}
}