// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: riskengine/riskengine.proto

package riskengine

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/nats-rpc/nrpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxRiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`   // v: required
	SignTx  string `protobuf:"bytes,2,opt,name=SignTx,proto3" json:"SignTx,omitempty"`   // v: required
	ChainId string `protobuf:"bytes,3,opt,name=ChainId,proto3" json:"ChainId,omitempty"` // v: required
}

func (x *TxRiskReq) Reset() {
	*x = TxRiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskengine_riskengine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxRiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRiskReq) ProtoMessage() {}

func (x *TxRiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskengine_riskengine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRiskReq.ProtoReflect.Descriptor instead.
func (*TxRiskReq) Descriptor() ([]byte, []int) {
	return file_riskengine_riskengine_proto_rawDescGZIP(), []int{0}
}

func (x *TxRiskReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TxRiskReq) GetSignTx() string {
	if x != nil {
		return x.SignTx
	}
	return ""
}

func (x *TxRiskReq) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type TxRiskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  int32  `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *TxRiskRes) Reset() {
	*x = TxRiskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskengine_riskengine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxRiskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRiskRes) ProtoMessage() {}

func (x *TxRiskRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskengine_riskengine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRiskRes.ProtoReflect.Descriptor instead.
func (*TxRiskRes) Descriptor() ([]byte, []int) {
	return file_riskengine_riskengine_proto_rawDescGZIP(), []int{1}
}

func (x *TxRiskRes) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *TxRiskRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// //
type TfaRiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// "in:bindPhone,bindMail,updatePhone,updateMail"
	Token    string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`       // v: required
	CodeType string `protobuf:"bytes,2,opt,name=CodeType,proto3" json:"CodeType,omitempty"` // v: required
}

func (x *TfaRiskReq) Reset() {
	*x = TfaRiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskengine_riskengine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TfaRiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TfaRiskReq) ProtoMessage() {}

func (x *TfaRiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskengine_riskengine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TfaRiskReq.ProtoReflect.Descriptor instead.
func (*TfaRiskReq) Descriptor() ([]byte, []int) {
	return file_riskengine_riskengine_proto_rawDescGZIP(), []int{2}
}

func (x *TfaRiskReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TfaRiskReq) GetCodeType() string {
	if x != nil {
		return x.CodeType
	}
	return ""
}

type TfaRiskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  int32  `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *TfaRiskRes) Reset() {
	*x = TfaRiskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskengine_riskengine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TfaRiskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TfaRiskRes) ProtoMessage() {}

func (x *TfaRiskRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskengine_riskengine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TfaRiskRes.ProtoReflect.Descriptor instead.
func (*TfaRiskRes) Descriptor() ([]byte, []int) {
	return file_riskengine_riskengine_proto_rawDescGZIP(), []int{3}
}

func (x *TfaRiskRes) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *TfaRiskRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_riskengine_riskengine_proto protoreflect.FileDescriptor

var file_riskengine_riskengine_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x69, 0x73, 0x6b, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x72, 0x69, 0x73,
	0x6b, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x72,
	0x69, 0x73, 0x6b, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x55, 0x0a, 0x09, 0x54, 0x78, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x54,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x78, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x2d, 0x0a, 0x09, 0x54, 0x78, 0x52,
	0x69, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x3e, 0x0a, 0x0a, 0x54, 0x66, 0x61, 0x52,
	0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x43, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x43, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2e, 0x0a, 0x0a, 0x54, 0x66, 0x61, 0x52,
	0x69, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x32, 0xc8, 0x01, 0x0a, 0x0a, 0x52, 0x69, 0x73,
	0x6b, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x52, 0x70, 0x63, 0x41, 0x6c,
	0x69, 0x76, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0a, 0x52, 0x70, 0x63, 0x52, 0x69, 0x73, 0x6b,
	0x54, 0x78, 0x73, 0x12, 0x15, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x2e, 0x54, 0x78, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x72, 0x69, 0x73,
	0x6b, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x54, 0x78, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0a, 0x52, 0x70, 0x63, 0x52, 0x69, 0x73, 0x6b, 0x54, 0x66,
	0x61, 0x12, 0x16, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x54,
	0x66, 0x61, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x72, 0x69, 0x73, 0x6b,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x54, 0x66, 0x61, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x72, 0x69, 0x73, 0x6b, 0x65, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_riskengine_riskengine_proto_rawDescOnce sync.Once
	file_riskengine_riskengine_proto_rawDescData = file_riskengine_riskengine_proto_rawDesc
)

func file_riskengine_riskengine_proto_rawDescGZIP() []byte {
	file_riskengine_riskengine_proto_rawDescOnce.Do(func() {
		file_riskengine_riskengine_proto_rawDescData = protoimpl.X.CompressGZIP(file_riskengine_riskengine_proto_rawDescData)
	})
	return file_riskengine_riskengine_proto_rawDescData
}

var file_riskengine_riskengine_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_riskengine_riskengine_proto_goTypes = []interface{}{
	(*TxRiskReq)(nil),   // 0: riskengine.TxRiskReq
	(*TxRiskRes)(nil),   // 1: riskengine.TxRiskRes
	(*TfaRiskReq)(nil),  // 2: riskengine.TfaRiskReq
	(*TfaRiskRes)(nil),  // 3: riskengine.TfaRiskRes
	(*empty.Empty)(nil), // 4: google.protobuf.Empty
}
var file_riskengine_riskengine_proto_depIdxs = []int32{
	4, // 0: riskengine.RiskEngine.RpcAlive:input_type -> google.protobuf.Empty
	0, // 1: riskengine.RiskEngine.RpcRiskTxs:input_type -> riskengine.TxRiskReq
	2, // 2: riskengine.RiskEngine.RpcRiskTfa:input_type -> riskengine.TfaRiskReq
	4, // 3: riskengine.RiskEngine.RpcAlive:output_type -> google.protobuf.Empty
	1, // 4: riskengine.RiskEngine.RpcRiskTxs:output_type -> riskengine.TxRiskRes
	3, // 5: riskengine.RiskEngine.RpcRiskTfa:output_type -> riskengine.TfaRiskRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_riskengine_riskengine_proto_init() }
func file_riskengine_riskengine_proto_init() {
	if File_riskengine_riskengine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_riskengine_riskengine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxRiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskengine_riskengine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxRiskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskengine_riskengine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TfaRiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskengine_riskengine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TfaRiskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_riskengine_riskengine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_riskengine_riskengine_proto_goTypes,
		DependencyIndexes: file_riskengine_riskengine_proto_depIdxs,
		MessageInfos:      file_riskengine_riskengine_proto_msgTypes,
	}.Build()
	File_riskengine_riskengine_proto = out.File
	file_riskengine_riskengine_proto_rawDesc = nil
	file_riskengine_riskengine_proto_goTypes = nil
	file_riskengine_riskengine_proto_depIdxs = nil
}
