server:
  name: "transAct"
  address:     ":8005"
  workId: 1
  cpuCore: 2
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

jaegerUrl: "127.0.0.1:6831"

logger:
  level : "all"
  stdout: true 
  rotateExpire: "1d"
  path: "./"

database:
  default:
  - link: "pgsql:postgres:123456@tcp(127.0.0.1:10100)/txs"
    role: "master"
  - link: "pgsql:postgres:123456@tcp(127.0.0.1:10101)/txs"
    role: "slave"
  transAct:
  - link: "pgsql:postgres:123456@tcp(127.0.0.1:10100)/transAct"
    role: "master"
  - link: "pgsql:postgres:123456@tcp(127.0.0.1:10101)/transAct"
    role: "slave"
cache:
  sessionDuration: 2000

nrpc:
  natsUrl: "127.0.0.1:4222"

# redis 
redis:
  default:
    address: 127.0.0.1:6379
    db:      1
  cache:
    address:     127.0.0.1:6379
    db:          2

userToken: "https://auth-dev.mixmarvel-sdk.com/info"

txdatarpc: "http://desktopuser:8004"

gfcli:
  gen:
    dao:
    - link:     "pgsql:postgres:123456@tcp(127.0.0.1:10100)/txs"
      tables:   "txs"
      jsonCase: "CamelLower"
