// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"txpusher/internal/dao/internal"
)

// internalContractruleDao is internal type for wrapping internal DAO implements.
type internalContractruleDao = *internal.ContractruleDao

// contractruleDao is the data access object for table contractrule.
// You can define custom methods on it to extend its functionality as you wish.
type contractruleDao struct {
	internalContractruleDao
}

var (
	// Contractrule is globally public accessible object for table contractrule operations.
	Contractrule = contractruleDao{
		internal.NewContractruleDao(),
	}
)

// Fill with you ideas below.
