// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"txpusher/internal/dao/internal"
)

// internalTxsDao is internal type for wrapping internal DAO implements.
type internalTxsDao = *internal.TxsDao

// txsDao is the data access object for table txs.
// You can define custom methods on it to extend its functionality as you wish.
type txsDao struct {
	internalTxsDao
}

var (
	// Txs is globally public accessible object for table txs operations.
	Txs = txsDao{
		internal.NewTxsDao(),
	}
)

// Fill with you ideas below.
