// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: riskctrl/riskctrl.proto

package riskctrl

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/nats-rpc/nrpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// /
type TfaRequestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// "in:bindPhone,bindMail,updatePhone,updateMail"
	Token    string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`       // v: required
	CodeType string `protobuf:"bytes,2,opt,name=CodeType,proto3" json:"CodeType,omitempty"` // v: required
}

func (x *TfaRequestReq) Reset() {
	*x = TfaRequestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TfaRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TfaRequestReq) ProtoMessage() {}

func (x *TfaRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TfaRequestReq.ProtoReflect.Descriptor instead.
func (*TfaRequestReq) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{0}
}

func (x *TfaRequestReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TfaRequestReq) GetCodeType() string {
	if x != nil {
		return x.CodeType
	}
	return ""
}

type TfaRequestRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiskSerial string   `protobuf:"bytes,1,opt,name=RiskSerial,proto3" json:"RiskSerial,omitempty"`
	VList      []string `protobuf:"bytes,2,rep,name=VList,proto3" json:"VList,omitempty"`
}

func (x *TfaRequestRes) Reset() {
	*x = TfaRequestRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TfaRequestRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TfaRequestRes) ProtoMessage() {}

func (x *TfaRequestRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TfaRequestRes.ProtoReflect.Descriptor instead.
func (*TfaRequestRes) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{1}
}

func (x *TfaRequestRes) GetRiskSerial() string {
	if x != nil {
		return x.RiskSerial
	}
	return ""
}

func (x *TfaRequestRes) GetVList() []string {
	if x != nil {
		return x.VList
	}
	return nil
}

// //
type TfaInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"` // v: required
}

func (x *TfaInfoReq) Reset() {
	*x = TfaInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TfaInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TfaInfoReq) ProtoMessage() {}

func (x *TfaInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TfaInfoReq.ProtoReflect.Descriptor instead.
func (*TfaInfoReq) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{2}
}

func (x *TfaInfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TfaInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phone       string `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	UpPhoneTime string `protobuf:"bytes,2,opt,name=UpPhoneTime,proto3" json:"UpPhoneTime,omitempty"`
	Mail        string `protobuf:"bytes,3,opt,name=Mail,proto3" json:"Mail,omitempty"`
	UpMailTime  string `protobuf:"bytes,4,opt,name=UpMailTime,proto3" json:"UpMailTime,omitempty"`
	UserId      string `protobuf:"bytes,5,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *TfaInfoRes) Reset() {
	*x = TfaInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TfaInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TfaInfoRes) ProtoMessage() {}

func (x *TfaInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TfaInfoRes.ProtoReflect.Descriptor instead.
func (*TfaInfoRes) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{3}
}

func (x *TfaInfoRes) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *TfaInfoRes) GetUpPhoneTime() string {
	if x != nil {
		return x.UpPhoneTime
	}
	return ""
}

func (x *TfaInfoRes) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *TfaInfoRes) GetUpMailTime() string {
	if x != nil {
		return x.UpMailTime
	}
	return ""
}

func (x *TfaInfoRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SendPhoneCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiskSerial string `protobuf:"bytes,1,opt,name=RiskSerial,proto3" json:"RiskSerial,omitempty"` // v: required
	// string Token = 2; // v: required
	UserId string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"` // v: required
	Phone  string `protobuf:"bytes,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
}

func (x *SendPhoneCodeReq) Reset() {
	*x = SendPhoneCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPhoneCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPhoneCodeReq) ProtoMessage() {}

func (x *SendPhoneCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPhoneCodeReq.ProtoReflect.Descriptor instead.
func (*SendPhoneCodeReq) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{4}
}

func (x *SendPhoneCodeReq) GetRiskSerial() string {
	if x != nil {
		return x.RiskSerial
	}
	return ""
}

func (x *SendPhoneCodeReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendPhoneCodeReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type SendPhoneCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  int32  `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *SendPhoneCodeRes) Reset() {
	*x = SendPhoneCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPhoneCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPhoneCodeRes) ProtoMessage() {}

func (x *SendPhoneCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPhoneCodeRes.ProtoReflect.Descriptor instead.
func (*SendPhoneCodeRes) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{5}
}

func (x *SendPhoneCodeRes) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *SendPhoneCodeRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// /
type SendMailCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiskSerial string `protobuf:"bytes,1,opt,name=RiskSerial,proto3" json:"RiskSerial,omitempty"` // v: required
	// string Token= 2; // v: required
	UserId string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"` // v: required
	Mail   string `protobuf:"bytes,3,opt,name=Mail,proto3" json:"Mail,omitempty"`
}

func (x *SendMailCodeReq) Reset() {
	*x = SendMailCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMailCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailCodeReq) ProtoMessage() {}

func (x *SendMailCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailCodeReq.ProtoReflect.Descriptor instead.
func (*SendMailCodeReq) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{6}
}

func (x *SendMailCodeReq) GetRiskSerial() string {
	if x != nil {
		return x.RiskSerial
	}
	return ""
}

func (x *SendMailCodeReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendMailCodeReq) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

type SendMailCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  int32  `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *SendMailCodeRes) Reset() {
	*x = SendMailCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMailCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailCodeRes) ProtoMessage() {}

func (x *SendMailCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailCodeRes.ProtoReflect.Descriptor instead.
func (*SendMailCodeRes) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{7}
}

func (x *SendMailCodeRes) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *SendMailCodeRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ///
type VerifyCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiskSerial string `protobuf:"bytes,1,opt,name=RiskSerial,proto3" json:"RiskSerial,omitempty"` // v: required
	// string Token = 2; // v: required
	UserId    string `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`       // v: required
	PhoneCode string `protobuf:"bytes,3,opt,name=PhoneCode,proto3" json:"PhoneCode,omitempty"` // v: required
	MailCode  string `protobuf:"bytes,4,opt,name=MailCode,proto3" json:"MailCode,omitempty"`   // v: required
}

func (x *VerifyCodeReq) Reset() {
	*x = VerifyCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeReq) ProtoMessage() {}

func (x *VerifyCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeReq.ProtoReflect.Descriptor instead.
func (*VerifyCodeReq) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyCodeReq) GetRiskSerial() string {
	if x != nil {
		return x.RiskSerial
	}
	return ""
}

func (x *VerifyCodeReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyCodeReq) GetPhoneCode() string {
	if x != nil {
		return x.PhoneCode
	}
	return ""
}

func (x *VerifyCodeReq) GetMailCode() string {
	if x != nil {
		return x.MailCode
	}
	return ""
}

type VerifyCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  int32  `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *VerifyCodeRes) Reset() {
	*x = VerifyCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeRes) ProtoMessage() {}

func (x *VerifyCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeRes.ProtoReflect.Descriptor instead.
func (*VerifyCodeRes) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyCodeRes) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *VerifyCodeRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ///
// /
type ContractRuleBriefsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId string `protobuf:"bytes,1,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	Kind    string `protobuf:"bytes,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *ContractRuleBriefsReq) Reset() {
	*x = ContractRuleBriefsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractRuleBriefsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRuleBriefsReq) ProtoMessage() {}

func (x *ContractRuleBriefsReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRuleBriefsReq.ProtoReflect.Descriptor instead.
func (*ContractRuleBriefsReq) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{10}
}

func (x *ContractRuleBriefsReq) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ContractRuleBriefsReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContractRuleBriefsReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ContractRuleBriefsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Briefs map[string]*ContractRuleBriefs `protobuf:"bytes,1,rep,name=Briefs,proto3" json:"Briefs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ContractRuleBriefsRes) Reset() {
	*x = ContractRuleBriefsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractRuleBriefsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRuleBriefsRes) ProtoMessage() {}

func (x *ContractRuleBriefsRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRuleBriefsRes.ProtoReflect.Descriptor instead.
func (*ContractRuleBriefsRes) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{11}
}

func (x *ContractRuleBriefsRes) GetBriefs() map[string]*ContractRuleBriefs {
	if x != nil {
		return x.Briefs
	}
	return nil
}

type ContractRuleBriefs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId string `protobuf:"bytes,1,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Kind    string `protobuf:"bytes,4,opt,name=Kind,proto3" json:"Kind,omitempty"`
}

func (x *ContractRuleBriefs) Reset() {
	*x = ContractRuleBriefs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractRuleBriefs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRuleBriefs) ProtoMessage() {}

func (x *ContractRuleBriefs) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRuleBriefs.ProtoReflect.Descriptor instead.
func (*ContractRuleBriefs) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{12}
}

func (x *ContractRuleBriefs) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ContractRuleBriefs) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ContractRuleBriefs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContractRuleBriefs) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ContractRuleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId string `protobuf:"bytes,1,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	Kind    string `protobuf:"bytes,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *ContractRuleReq) Reset() {
	*x = ContractRuleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractRuleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRuleReq) ProtoMessage() {}

func (x *ContractRuleReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRuleReq.ProtoReflect.Descriptor instead.
func (*ContractRuleReq) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{13}
}

func (x *ContractRuleReq) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ContractRuleReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContractRuleReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ContractRuleRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contract             string   `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind                 string   `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	MethodName           string   `protobuf:"bytes,4,opt,name=methodName,proto3" json:"methodName,omitempty"`
	MethodSig            string   `protobuf:"bytes,5,opt,name=methodSig,proto3" json:"methodSig,omitempty"`
	MethodFromField      string   `protobuf:"bytes,6,opt,name=methodFromField,proto3" json:"methodFromField,omitempty"`
	MethodToField        string   `protobuf:"bytes,7,opt,name=methodToField,proto3" json:"methodToField,omitempty"`
	MethodValueField     string   `protobuf:"bytes,8,opt,name=methodValueField,proto3" json:"methodValueField,omitempty"`
	EventName            string   `protobuf:"bytes,9,opt,name=eventName,proto3" json:"eventName,omitempty"`
	EventSig             string   `protobuf:"bytes,10,opt,name=eventSig,proto3" json:"eventSig,omitempty"`
	EventTopic           string   `protobuf:"bytes,11,opt,name=eventTopic,proto3" json:"eventTopic,omitempty"`
	EventFromField       string   `protobuf:"bytes,12,opt,name=eventFromField,proto3" json:"eventFromField,omitempty"`
	EventToField         string   `protobuf:"bytes,13,opt,name=eventToField,proto3" json:"eventToField,omitempty"`
	EventValueField      string   `protobuf:"bytes,14,opt,name=eventValueField,proto3" json:"eventValueField,omitempty"`
	WhiteAddrList        []string `protobuf:"bytes,15,rep,name=WhiteAddrList,proto3" json:"WhiteAddrList,omitempty"`
	ThresholdBigintBytes []byte   `protobuf:"bytes,16,opt,name=threshold_bigint_bytes,json=thresholdBigintBytes,proto3" json:"threshold_bigint_bytes,omitempty"`
}

func (x *ContractRuleRes) Reset() {
	*x = ContractRuleRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractRuleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractRuleRes) ProtoMessage() {}

func (x *ContractRuleRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractRuleRes.ProtoReflect.Descriptor instead.
func (*ContractRuleRes) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{14}
}

func (x *ContractRuleRes) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *ContractRuleRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContractRuleRes) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContractRuleRes) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *ContractRuleRes) GetMethodSig() string {
	if x != nil {
		return x.MethodSig
	}
	return ""
}

func (x *ContractRuleRes) GetMethodFromField() string {
	if x != nil {
		return x.MethodFromField
	}
	return ""
}

func (x *ContractRuleRes) GetMethodToField() string {
	if x != nil {
		return x.MethodToField
	}
	return ""
}

func (x *ContractRuleRes) GetMethodValueField() string {
	if x != nil {
		return x.MethodValueField
	}
	return ""
}

func (x *ContractRuleRes) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *ContractRuleRes) GetEventSig() string {
	if x != nil {
		return x.EventSig
	}
	return ""
}

func (x *ContractRuleRes) GetEventTopic() string {
	if x != nil {
		return x.EventTopic
	}
	return ""
}

func (x *ContractRuleRes) GetEventFromField() string {
	if x != nil {
		return x.EventFromField
	}
	return ""
}

func (x *ContractRuleRes) GetEventToField() string {
	if x != nil {
		return x.EventToField
	}
	return ""
}

func (x *ContractRuleRes) GetEventValueField() string {
	if x != nil {
		return x.EventValueField
	}
	return ""
}

func (x *ContractRuleRes) GetWhiteAddrList() []string {
	if x != nil {
		return x.WhiteAddrList
	}
	return nil
}

func (x *ContractRuleRes) GetThresholdBigintBytes() []byte {
	if x != nil {
		return x.ThresholdBigintBytes
	}
	return nil
}

// /
type ContractAbiBriefsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId string `protobuf:"bytes,1,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	Kind    string `protobuf:"bytes,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *ContractAbiBriefsReq) Reset() {
	*x = ContractAbiBriefsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractAbiBriefsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractAbiBriefsReq) ProtoMessage() {}

func (x *ContractAbiBriefsReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractAbiBriefsReq.ProtoReflect.Descriptor instead.
func (*ContractAbiBriefsReq) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{15}
}

func (x *ContractAbiBriefsReq) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ContractAbiBriefsReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContractAbiBriefsReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ContractAbiBrief struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId string `protobuf:"bytes,1,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Kind    string `protobuf:"bytes,4,opt,name=Kind,proto3" json:"Kind,omitempty"`
}

func (x *ContractAbiBrief) Reset() {
	*x = ContractAbiBrief{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractAbiBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractAbiBrief) ProtoMessage() {}

func (x *ContractAbiBrief) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractAbiBrief.ProtoReflect.Descriptor instead.
func (*ContractAbiBrief) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{16}
}

func (x *ContractAbiBrief) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ContractAbiBrief) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ContractAbiBrief) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContractAbiBrief) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type ContractAbiBriefsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Briefs map[string]*ContractAbiBrief `protobuf:"bytes,1,rep,name=Briefs,proto3" json:"Briefs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ContractAbiBriefsRes) Reset() {
	*x = ContractAbiBriefsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractAbiBriefsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractAbiBriefsRes) ProtoMessage() {}

func (x *ContractAbiBriefsRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractAbiBriefsRes.ProtoReflect.Descriptor instead.
func (*ContractAbiBriefsRes) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{17}
}

func (x *ContractAbiBriefsRes) GetBriefs() map[string]*ContractAbiBrief {
	if x != nil {
		return x.Briefs
	}
	return nil
}

type ContractAbiReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId string `protobuf:"bytes,1,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	Kind    string `protobuf:"bytes,2,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *ContractAbiReq) Reset() {
	*x = ContractAbiReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractAbiReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractAbiReq) ProtoMessage() {}

func (x *ContractAbiReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractAbiReq.ProtoReflect.Descriptor instead.
func (*ContractAbiReq) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{18}
}

func (x *ContractAbiReq) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ContractAbiReq) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ContractAbiReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ContractAbiRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ContractName    string `protobuf:"bytes,2,opt,name=ContractName,proto3" json:"ContractName,omitempty"`
	ContractAddress string `protobuf:"bytes,3,opt,name=ContractAddress,proto3" json:"ContractAddress,omitempty"`
	ChainId         string `protobuf:"bytes,4,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	AbiContent      string `protobuf:"bytes,5,opt,name=AbiContent,proto3" json:"AbiContent,omitempty"`
	ContractKind    string `protobuf:"bytes,6,opt,name=ContractKind,proto3" json:"ContractKind,omitempty"`
}

func (x *ContractAbiRes) Reset() {
	*x = ContractAbiRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractAbiRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractAbiRes) ProtoMessage() {}

func (x *ContractAbiRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractAbiRes.ProtoReflect.Descriptor instead.
func (*ContractAbiRes) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{19}
}

func (x *ContractAbiRes) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContractAbiRes) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *ContractAbiRes) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *ContractAbiRes) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ContractAbiRes) GetAbiContent() string {
	if x != nil {
		return x.AbiContent
	}
	return ""
}

func (x *ContractAbiRes) GetContractKind() string {
	if x != nil {
		return x.ContractKind
	}
	return ""
}

// //
// /
type RiskTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contract string `protobuf:"bytes,1,opt,name=Contract,proto3" json:"Contract,omitempty"` // v: required
	TxData   string `protobuf:"bytes,2,opt,name=TxData,proto3" json:"TxData,omitempty"`     // v: required
}

func (x *RiskTx) Reset() {
	*x = RiskTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiskTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskTx) ProtoMessage() {}

func (x *RiskTx) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskTx.ProtoReflect.Descriptor instead.
func (*RiskTx) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{20}
}

func (x *RiskTx) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *RiskTx) GetTxData() string {
	if x != nil {
		return x.TxData
	}
	return ""
}

type TxRequestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`   // v: required
	Address string `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"` // v: required
	// //
	SignTxData string `protobuf:"bytes,3,opt,name=SignTxData,proto3" json:"SignTxData,omitempty"` // v: required
	ChainId    string `protobuf:"bytes,4,opt,name=ChainId,proto3" json:"ChainId,omitempty"`       // v: required
}

func (x *TxRequestReq) Reset() {
	*x = TxRequestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxRequestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRequestReq) ProtoMessage() {}

func (x *TxRequestReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRequestReq.ProtoReflect.Descriptor instead.
func (*TxRequestReq) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{21}
}

func (x *TxRequestReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TxRequestReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TxRequestReq) GetSignTxData() string {
	if x != nil {
		return x.SignTxData
	}
	return ""
}

func (x *TxRequestReq) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type TxRequestRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok         int32    `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg        string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	RiskSerial string   `protobuf:"bytes,3,opt,name=RiskSerial,proto3" json:"RiskSerial,omitempty"`
	RiskKind   []string `protobuf:"bytes,4,rep,name=RiskKind,proto3" json:"RiskKind,omitempty"`
}

func (x *TxRequestRes) Reset() {
	*x = TxRequestRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxRequestRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRequestRes) ProtoMessage() {}

func (x *TxRequestRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRequestRes.ProtoReflect.Descriptor instead.
func (*TxRequestRes) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{22}
}

func (x *TxRequestRes) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *TxRequestRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TxRequestRes) GetRiskSerial() string {
	if x != nil {
		return x.RiskSerial
	}
	return ""
}

func (x *TxRequestRes) GetRiskKind() []string {
	if x != nil {
		return x.RiskKind
	}
	return nil
}

// //
type TFARiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"` // v: required
	Type   string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`     // v: required
	Mail   string `protobuf:"bytes,3,opt,name=Mail,proto3" json:"Mail,omitempty"`
	Phone  string `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
}

func (x *TFARiskReq) Reset() {
	*x = TFARiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TFARiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFARiskReq) ProtoMessage() {}

func (x *TFARiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFARiskReq.ProtoReflect.Descriptor instead.
func (*TFARiskReq) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{23}
}

func (x *TFARiskReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TFARiskReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TFARiskReq) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *TFARiskReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type TFARiskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok         int32  `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg        string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	RiskSerial string `protobuf:"bytes,3,opt,name=RiskSerial,proto3" json:"RiskSerial,omitempty"`
}

func (x *TFARiskRes) Reset() {
	*x = TFARiskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riskctrl_riskctrl_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TFARiskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFARiskRes) ProtoMessage() {}

func (x *TFARiskRes) ProtoReflect() protoreflect.Message {
	mi := &file_riskctrl_riskctrl_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFARiskRes.ProtoReflect.Descriptor instead.
func (*TFARiskRes) Descriptor() ([]byte, []int) {
	return file_riskctrl_riskctrl_proto_rawDescGZIP(), []int{24}
}

func (x *TFARiskRes) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *TFARiskRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TFARiskRes) GetRiskSerial() string {
	if x != nil {
		return x.RiskSerial
	}
	return ""
}

var File_riskctrl_riskctrl_proto protoreflect.FileDescriptor

var file_riskctrl_riskctrl_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2f, 0x72, 0x69, 0x73, 0x6b, 0x63,
	0x74, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x69, 0x73, 0x6b, 0x63,
	0x74, 0x72, 0x6c, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0a, 0x6e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x0d,
	0x54, 0x66, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x45, 0x0a, 0x0d, 0x54, 0x66, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x56, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x56, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x0a, 0x54, 0x66, 0x61, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x90, 0x01, 0x0a,
	0x0a, 0x54, 0x66, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x70, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x55, 0x70, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x4d, 0x61, 0x69,
	0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x70, 0x4d,
	0x61, 0x69, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x60, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x22, 0x34, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x5d, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x69,
	0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x22, 0x33, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61,
	0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x81, 0x01, 0x0a, 0x0d,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a,
	0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x16, 0x0a,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x31, 0x0a, 0x0d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x4f, 0x6b,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x22, 0x5f, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x75,
	0x6c, 0x65, 0x42, 0x72, 0x69, 0x65, 0x66, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0xb5, 0x01, 0x0a, 0x15, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x52, 0x75, 0x6c, 0x65, 0x42, 0x72, 0x69, 0x65, 0x66, 0x73, 0x52, 0x65, 0x73, 0x12, 0x43, 0x0a,
	0x06, 0x42, 0x72, 0x69, 0x65, 0x66, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x52, 0x75, 0x6c, 0x65, 0x42, 0x72, 0x69, 0x65, 0x66, 0x73, 0x52, 0x65, 0x73, 0x2e, 0x42,
	0x72, 0x69, 0x65, 0x66, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x42, 0x72, 0x69, 0x65,
	0x66, 0x73, 0x1a, 0x57, 0x0a, 0x0b, 0x42, 0x72, 0x69, 0x65, 0x66, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x42, 0x72, 0x69, 0x65, 0x66, 0x73,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x70, 0x0a, 0x12, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x42, 0x72, 0x69, 0x65, 0x66,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x69, 0x6e,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x22, 0x59, 0x0a,
	0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x69,
	0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xbb, 0x04, 0x0a, 0x0f, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x53, 0x69, 0x67, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x53, 0x69, 0x67, 0x12, 0x28,
	0x0a, 0x0f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x46,
	0x72, 0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x54, 0x6f, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x54, 0x6f, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2a,
	0x0a, 0x10, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x53, 0x69, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x53, 0x69, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x6f,
	0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x28, 0x0a, 0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x57, 0x68,
	0x69, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0f, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0d, 0x57, 0x68, 0x69, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x34, 0x0a, 0x16, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x5f, 0x62, 0x69,
	0x67, 0x69, 0x6e, 0x74, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x14, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x42, 0x69, 0x67, 0x69, 0x6e,
	0x74, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x5e, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x41, 0x62, 0x69, 0x42, 0x72, 0x69, 0x65, 0x66, 0x73, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x6e, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x41, 0x62, 0x69, 0x42, 0x72, 0x69, 0x65, 0x66, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x22, 0xb1, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x41, 0x62, 0x69, 0x42, 0x72, 0x69, 0x65, 0x66, 0x73, 0x52, 0x65, 0x73, 0x12,
	0x42, 0x0a, 0x06, 0x42, 0x72, 0x69, 0x65, 0x66, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x41, 0x62, 0x69, 0x42, 0x72, 0x69, 0x65, 0x66, 0x73, 0x52, 0x65, 0x73, 0x2e,
	0x42, 0x72, 0x69, 0x65, 0x66, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x42, 0x72, 0x69,
	0x65, 0x66, 0x73, 0x1a, 0x55, 0x0a, 0x0b, 0x42, 0x72, 0x69, 0x65, 0x66, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x62, 0x69, 0x42, 0x72, 0x69, 0x65, 0x66, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x58, 0x0a, 0x0e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x62, 0x69, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0xcc, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x41, 0x62, 0x69, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x41, 0x62, 0x69, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x62, 0x69, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4b,
	0x69, 0x6e, 0x64, 0x22, 0x3c, 0x0a, 0x06, 0x52, 0x69, 0x73, 0x6b, 0x54, 0x78, 0x12, 0x1a, 0x0a,
	0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x78, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x78, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x7a, 0x0a, 0x0c, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x78, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x78, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x6c, 0x0a,
	0x0c, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12,
	0x1e, 0x0a, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x52, 0x69, 0x73, 0x6b, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x52, 0x69, 0x73, 0x6b, 0x4b, 0x69, 0x6e, 0x64, 0x22, 0x62, 0x0a, 0x0a, 0x54,
	0x46, 0x41, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x22,
	0x4e, 0x0a, 0x0a, 0x54, 0x46, 0x41, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x10, 0x0a,
	0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12,
	0x1e, 0x0a, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x32,
	0xea, 0x03, 0x0a, 0x08, 0x52, 0x69, 0x73, 0x6b, 0x43, 0x74, 0x72, 0x6c, 0x12, 0x3c, 0x0a, 0x08,
	0x52, 0x70, 0x63, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0d, 0x52, 0x70,
	0x63, 0x54, 0x78, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x72, 0x69,
	0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x54,
	0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x43, 0x0a,
	0x0d, 0x52, 0x70, 0x63, 0x54, 0x66, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x54, 0x66, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74,
	0x72, 0x6c, 0x2e, 0x54, 0x66, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0a, 0x52, 0x70, 0x63, 0x54, 0x66, 0x61, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x14, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x54, 0x66, 0x61, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72,
	0x6c, 0x2e, 0x54, 0x66, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4c,
	0x0a, 0x10, 0x52, 0x70, 0x63, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1a, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0f,
	0x52, 0x70, 0x63, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x19, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x72, 0x69, 0x73,
	0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0d, 0x52, 0x70, 0x63, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63,
	0x74, 0x72, 0x6c, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09,
	0x2f, 0x72, 0x69, 0x73, 0x6b, 0x63, 0x74, 0x72, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_riskctrl_riskctrl_proto_rawDescOnce sync.Once
	file_riskctrl_riskctrl_proto_rawDescData = file_riskctrl_riskctrl_proto_rawDesc
)

func file_riskctrl_riskctrl_proto_rawDescGZIP() []byte {
	file_riskctrl_riskctrl_proto_rawDescOnce.Do(func() {
		file_riskctrl_riskctrl_proto_rawDescData = protoimpl.X.CompressGZIP(file_riskctrl_riskctrl_proto_rawDescData)
	})
	return file_riskctrl_riskctrl_proto_rawDescData
}

var file_riskctrl_riskctrl_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_riskctrl_riskctrl_proto_goTypes = []interface{}{
	(*TfaRequestReq)(nil),         // 0: riskctrl.TfaRequestReq
	(*TfaRequestRes)(nil),         // 1: riskctrl.TfaRequestRes
	(*TfaInfoReq)(nil),            // 2: riskctrl.TfaInfoReq
	(*TfaInfoRes)(nil),            // 3: riskctrl.TfaInfoRes
	(*SendPhoneCodeReq)(nil),      // 4: riskctrl.SendPhoneCodeReq
	(*SendPhoneCodeRes)(nil),      // 5: riskctrl.SendPhoneCodeRes
	(*SendMailCodeReq)(nil),       // 6: riskctrl.SendMailCodeReq
	(*SendMailCodeRes)(nil),       // 7: riskctrl.SendMailCodeRes
	(*VerifyCodeReq)(nil),         // 8: riskctrl.VerifyCodeReq
	(*VerifyCodeRes)(nil),         // 9: riskctrl.VerifyCodeRes
	(*ContractRuleBriefsReq)(nil), // 10: riskctrl.ContractRuleBriefsReq
	(*ContractRuleBriefsRes)(nil), // 11: riskctrl.ContractRuleBriefsRes
	(*ContractRuleBriefs)(nil),    // 12: riskctrl.ContractRuleBriefs
	(*ContractRuleReq)(nil),       // 13: riskctrl.ContractRuleReq
	(*ContractRuleRes)(nil),       // 14: riskctrl.ContractRuleRes
	(*ContractAbiBriefsReq)(nil),  // 15: riskctrl.ContractAbiBriefsReq
	(*ContractAbiBrief)(nil),      // 16: riskctrl.ContractAbiBrief
	(*ContractAbiBriefsRes)(nil),  // 17: riskctrl.ContractAbiBriefsRes
	(*ContractAbiReq)(nil),        // 18: riskctrl.ContractAbiReq
	(*ContractAbiRes)(nil),        // 19: riskctrl.ContractAbiRes
	(*RiskTx)(nil),                // 20: riskctrl.RiskTx
	(*TxRequestReq)(nil),          // 21: riskctrl.TxRequestReq
	(*TxRequestRes)(nil),          // 22: riskctrl.TxRequestRes
	(*TFARiskReq)(nil),            // 23: riskctrl.TFARiskReq
	(*TFARiskRes)(nil),            // 24: riskctrl.TFARiskRes
	nil,                           // 25: riskctrl.ContractRuleBriefsRes.BriefsEntry
	nil,                           // 26: riskctrl.ContractAbiBriefsRes.BriefsEntry
	(*empty.Empty)(nil),           // 27: google.protobuf.Empty
}
var file_riskctrl_riskctrl_proto_depIdxs = []int32{
	25, // 0: riskctrl.ContractRuleBriefsRes.Briefs:type_name -> riskctrl.ContractRuleBriefsRes.BriefsEntry
	26, // 1: riskctrl.ContractAbiBriefsRes.Briefs:type_name -> riskctrl.ContractAbiBriefsRes.BriefsEntry
	12, // 2: riskctrl.ContractRuleBriefsRes.BriefsEntry.value:type_name -> riskctrl.ContractRuleBriefs
	16, // 3: riskctrl.ContractAbiBriefsRes.BriefsEntry.value:type_name -> riskctrl.ContractAbiBrief
	27, // 4: riskctrl.RiskCtrl.RpcAlive:input_type -> google.protobuf.Empty
	21, // 5: riskctrl.RiskCtrl.RpcTxsRequest:input_type -> riskctrl.TxRequestReq
	0,  // 6: riskctrl.RiskCtrl.RpcTfaRequest:input_type -> riskctrl.TfaRequestReq
	2,  // 7: riskctrl.RiskCtrl.RpcTfaInfo:input_type -> riskctrl.TfaInfoReq
	4,  // 8: riskctrl.RiskCtrl.RpcSendPhoneCode:input_type -> riskctrl.SendPhoneCodeReq
	6,  // 9: riskctrl.RiskCtrl.RpcSendMailCode:input_type -> riskctrl.SendMailCodeReq
	8,  // 10: riskctrl.RiskCtrl.RpcVerifyCode:input_type -> riskctrl.VerifyCodeReq
	27, // 11: riskctrl.RiskCtrl.RpcAlive:output_type -> google.protobuf.Empty
	22, // 12: riskctrl.RiskCtrl.RpcTxsRequest:output_type -> riskctrl.TxRequestRes
	1,  // 13: riskctrl.RiskCtrl.RpcTfaRequest:output_type -> riskctrl.TfaRequestRes
	3,  // 14: riskctrl.RiskCtrl.RpcTfaInfo:output_type -> riskctrl.TfaInfoRes
	5,  // 15: riskctrl.RiskCtrl.RpcSendPhoneCode:output_type -> riskctrl.SendPhoneCodeRes
	7,  // 16: riskctrl.RiskCtrl.RpcSendMailCode:output_type -> riskctrl.SendMailCodeRes
	9,  // 17: riskctrl.RiskCtrl.RpcVerifyCode:output_type -> riskctrl.VerifyCodeRes
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_riskctrl_riskctrl_proto_init() }
func file_riskctrl_riskctrl_proto_init() {
	if File_riskctrl_riskctrl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_riskctrl_riskctrl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TfaRequestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TfaRequestRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TfaInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TfaInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPhoneCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPhoneCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMailCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMailCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractRuleBriefsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractRuleBriefsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractRuleBriefs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractRuleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractRuleRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractAbiBriefsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractAbiBrief); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractAbiBriefsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractAbiReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractAbiRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiskTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxRequestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxRequestRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TFARiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riskctrl_riskctrl_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TFARiskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_riskctrl_riskctrl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_riskctrl_riskctrl_proto_goTypes,
		DependencyIndexes: file_riskctrl_riskctrl_proto_depIdxs,
		MessageInfos:      file_riskctrl_riskctrl_proto_msgTypes,
	}.Build()
	File_riskctrl_riskctrl_proto = out.File
	file_riskctrl_riskctrl_proto_rawDesc = nil
	file_riskctrl_riskctrl_proto_goTypes = nil
	file_riskctrl_riskctrl_proto_depIdxs = nil
}
