// This code was autogenerated from riskctrl/riskctrl.proto, do not edit.
package riskctrl

import (
	"context"
	"log"
	"time"

	"google.golang.org/protobuf/proto"
	"github.com/nats-io/nats.go"
	github_com_golang_protobuf_ptypes_empty "github.com/golang/protobuf/ptypes/empty"
	"github.com/nats-rpc/nrpc"
)

// RiskCtrlServer is the interface that providers of the service
// RiskCtrl should implement.
type RiskCtrlServer interface {
	RpcAlive(ctx context.Context, req *github_com_golang_protobuf_ptypes_empty.Empty) (*github_com_golang_protobuf_ptypes_empty.Empty, error)
	RpcTxsRequest(ctx context.Context, req *TxRequestReq) (*TxRequestRes, error)
	RpcTfaRequest(ctx context.Context, req *TfaRequestReq) (*TfaRequestRes, error)
	RpcTfaInfo(ctx context.Context, req *TfaInfoReq) (*TfaInfoRes, error)
	RpcSendPhoneCode(ctx context.Context, req *SendPhoneCodeReq) (*SendPhoneCodeRes, error)
	RpcSendMailCode(ctx context.Context, req *SendMailCodeReq) (*SendMailCodeRes, error)
	RpcVerifyCode(ctx context.Context, req *VerifyCodeReq) (*VerifyCodeRes, error)
}

// RiskCtrlHandler provides a NATS subscription handler that can serve a
// subscription using a given RiskCtrlServer implementation.
type RiskCtrlHandler struct {
	ctx     context.Context
	workers *nrpc.WorkerPool
	nc      nrpc.NatsConn
	server  RiskCtrlServer

	encodings []string
}

func NewRiskCtrlHandler(ctx context.Context, nc nrpc.NatsConn, s RiskCtrlServer) *RiskCtrlHandler {
	return &RiskCtrlHandler{
		ctx:    ctx,
		nc:     nc,
		server: s,

		encodings: []string{"protobuf"},
	}
}

func NewRiskCtrlConcurrentHandler(workers *nrpc.WorkerPool, nc nrpc.NatsConn, s RiskCtrlServer) *RiskCtrlHandler {
	return &RiskCtrlHandler{
		workers: workers,
		nc:      nc,
		server:  s,
	}
}

// SetEncodings sets the output encodings when using a '*Publish' function
func (h *RiskCtrlHandler) SetEncodings(encodings []string) {
	h.encodings = encodings
}

func (h *RiskCtrlHandler) Subject() string {
	return "RiskCtrl.>"
}

func (h *RiskCtrlHandler) Handler(msg *nats.Msg) {
	var ctx context.Context
	if h.workers != nil {
		ctx = h.workers.Context
	} else {
		ctx = h.ctx
	}
	request := nrpc.NewRequest(ctx, h.nc, msg.Subject, msg.Reply)
	// extract method name & encoding from subject
	_, _, name, tail, err := nrpc.ParseSubject(
		"", 0, "RiskCtrl", 0, msg.Subject)
	if err != nil {
		log.Printf("RiskCtrlHanlder: RiskCtrl subject parsing failed: %v", err)
		return
	}

	request.MethodName = name
	request.SubjectTail = tail

	// call handler and form response
	var immediateError *nrpc.Error
	switch name {
	case "RpcAlive":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("RpcAliveHanlder: RpcAlive subject parsing failed: %v", err)
			break
		}
		var req github_com_golang_protobuf_ptypes_empty.Empty
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("RpcAliveHandler: RpcAlive request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.RpcAlive(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	case "RpcTxsRequest":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("RpcTxsRequestHanlder: RpcTxsRequest subject parsing failed: %v", err)
			break
		}
		var req TxRequestReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("RpcTxsRequestHandler: RpcTxsRequest request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.RpcTxsRequest(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	case "RpcTfaRequest":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("RpcTfaRequestHanlder: RpcTfaRequest subject parsing failed: %v", err)
			break
		}
		var req TfaRequestReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("RpcTfaRequestHandler: RpcTfaRequest request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.RpcTfaRequest(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	case "RpcTfaInfo":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("RpcTfaInfoHanlder: RpcTfaInfo subject parsing failed: %v", err)
			break
		}
		var req TfaInfoReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("RpcTfaInfoHandler: RpcTfaInfo request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.RpcTfaInfo(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	case "RpcSendPhoneCode":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("RpcSendPhoneCodeHanlder: RpcSendPhoneCode subject parsing failed: %v", err)
			break
		}
		var req SendPhoneCodeReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("RpcSendPhoneCodeHandler: RpcSendPhoneCode request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.RpcSendPhoneCode(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	case "RpcSendMailCode":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("RpcSendMailCodeHanlder: RpcSendMailCode subject parsing failed: %v", err)
			break
		}
		var req SendMailCodeReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("RpcSendMailCodeHandler: RpcSendMailCode request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.RpcSendMailCode(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	case "RpcVerifyCode":
		_, request.Encoding, err = nrpc.ParseSubjectTail(0, request.SubjectTail)
		if err != nil {
			log.Printf("RpcVerifyCodeHanlder: RpcVerifyCode subject parsing failed: %v", err)
			break
		}
		var req VerifyCodeReq
		if err := nrpc.Unmarshal(request.Encoding, msg.Data, &req); err != nil {
			log.Printf("RpcVerifyCodeHandler: RpcVerifyCode request unmarshal failed: %v", err)
			immediateError = &nrpc.Error{
				Type: nrpc.Error_CLIENT,
				Message: "bad request received: " + err.Error(),
			}
		} else {
			request.Handler = func(ctx context.Context)(proto.Message, error){
				innerResp, err := h.server.RpcVerifyCode(ctx, &req)
				if err != nil {
					return nil, err
				}
				return innerResp, err
			}
		}
	default:
		log.Printf("RiskCtrlHandler: unknown name %q", name)
		immediateError = &nrpc.Error{
			Type: nrpc.Error_CLIENT,
			Message: "unknown name: " + name,
		}
	}
	if immediateError == nil {
		if h.workers != nil {
			// Try queuing the request
			if err := h.workers.QueueRequest(request); err != nil {
				log.Printf("nrpc: Error queuing the request: %s", err)
			}
		} else {
			// Run the handler synchronously
			request.RunAndReply()
		}
	}

	if immediateError != nil {
		if err := request.SendReply(nil, immediateError); err != nil {
			log.Printf("RiskCtrlHandler: RiskCtrl handler failed to publish the response: %s", err)
		}
	} else {
	}
}

type RiskCtrlClient struct {
	nc      nrpc.NatsConn
	Subject string
	Encoding string
	Timeout time.Duration
}

func NewRiskCtrlClient(nc nrpc.NatsConn) *RiskCtrlClient {
	return &RiskCtrlClient{
		nc:      nc,
		Subject: "RiskCtrl",
		Encoding: "protobuf",
		Timeout: 5 * time.Second,
	}
}

func (c *RiskCtrlClient) RpcAlive(req *github_com_golang_protobuf_ptypes_empty.Empty) (*github_com_golang_protobuf_ptypes_empty.Empty, error) {

	subject := c.Subject + "." + "RpcAlive"

	// call
	var resp = github_com_golang_protobuf_ptypes_empty.Empty{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *RiskCtrlClient) RpcTxsRequest(req *TxRequestReq) (*TxRequestRes, error) {

	subject := c.Subject + "." + "RpcTxsRequest"

	// call
	var resp = TxRequestRes{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *RiskCtrlClient) RpcTfaRequest(req *TfaRequestReq) (*TfaRequestRes, error) {

	subject := c.Subject + "." + "RpcTfaRequest"

	// call
	var resp = TfaRequestRes{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *RiskCtrlClient) RpcTfaInfo(req *TfaInfoReq) (*TfaInfoRes, error) {

	subject := c.Subject + "." + "RpcTfaInfo"

	// call
	var resp = TfaInfoRes{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *RiskCtrlClient) RpcSendPhoneCode(req *SendPhoneCodeReq) (*SendPhoneCodeRes, error) {

	subject := c.Subject + "." + "RpcSendPhoneCode"

	// call
	var resp = SendPhoneCodeRes{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *RiskCtrlClient) RpcSendMailCode(req *SendMailCodeReq) (*SendMailCodeRes, error) {

	subject := c.Subject + "." + "RpcSendMailCode"

	// call
	var resp = SendMailCodeRes{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

func (c *RiskCtrlClient) RpcVerifyCode(req *VerifyCodeReq) (*VerifyCodeRes, error) {

	subject := c.Subject + "." + "RpcVerifyCode"

	// call
	var resp = VerifyCodeRes{}
	if err := nrpc.Call(req, &resp, c.nc, subject, c.Encoding, c.Timeout); err != nil {
		return nil, err
	}

	return &resp, nil
}

type Client struct {
	nc      nrpc.NatsConn
	defaultEncoding string
	defaultTimeout time.Duration
	RiskCtrl *RiskCtrlClient
}

func NewClient(nc nrpc.NatsConn) *Client {
	c := Client{
		nc: nc,
		defaultEncoding: "protobuf",
		defaultTimeout: 5*time.Second,
	}
	c.RiskCtrl = NewRiskCtrlClient(nc)
	return &c
}

func (c *Client) SetEncoding(encoding string) {
	c.defaultEncoding = encoding
	if c.RiskCtrl != nil {
		c.RiskCtrl.Encoding = encoding
	}
}

func (c *Client) SetTimeout(t time.Duration) {
	c.defaultTimeout = t
	if c.RiskCtrl != nil {
		c.RiskCtrl.Timeout = t
	}
}